spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ForgeFlow
    username: postgres
    password: 111

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration