spring:
  application:
    name: backend

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/ForgeFlow
    username: postgres
    password: 111

  jpa:
    hibernate:
      ddl-auto: validate